### ISSUE TITLE
Make the address clickable and open google maps

### ISSUE THREAD

**Issue by liester** [opennebraska/landlord#32]

**Comment by jhannah** [comment]
Looks like this URL pattern will do it:
e.g.: 9320 J ST OMAHA NE
http://maps.google.com/?q=9320%20J%20ST%20OMAHA%20NE
(In our meeting yesterday @elviejito said he didn't know who would use this feature if it's implemented.)

**Comment by ronaldewatts** [comment]
What if instead of just clicking on an address and opening Google maps, there was an integrated map with markers for the low condition addresses (think of something like the Zillow map)?  My thought here is that if someone is looking in an area they might be able to easily see which rental spots to avoid.

@eis95 @dodgees

**Comment by ed-snodgrass** [comment]
I like the embedded map idea.

**Comment by ronaldewatts** [comment]
🤔 Well a problem with this is that Google now charges for their map usage.  We would have to look into the [Google Public Programs](https://developers.google.com/maps/billing/public-programs) to see if we could get monthly credits.  Bummer.

**Comment by ronaldewatts** [comment]
The primary request with this, a map link to the address, was resolved with https://github.com/opennebraska/landlord/pull/72.  For now not going to worry about the embedded map idea because of associated costs.
