### ISSUE TITLE
Show links on app bar for full screen or  drawer for mobile

### ISSUE THREAD

**Issue by dodgees** [opennebraska/landlord#39]
I think hiding the links to different pages in the hamburger menu makes the website harder to navigate for some users. Would be nice to have a responsive drawer instead, where the links are on the header for full screen and in the responsive drawer with the hamburger menu for smaller screens.

**Comment by ronaldewatts** [comment]
What if instead of pushing the items into the Title Bar the drawer was just responsive, meaning always stays open on wide enough screens.  Also, for those smaller screens it should probably auto-close after selection.  I think standard material design would keep navigation within the drawer or or bottom nav (https://material.io/components/bottom-navigation).

**Comment by dodgees** [comment]
Go for it, Ron. Make it look good 👍

**Comment by ed-snodgrass** [comment]
i agree that it is a good idea. Might also provide a good example for the nav on the next project

**Comment by ronaldewatts** [comment]
Here's what it looks like

![Uploading landlord_39_720p.gif…]()

**Comment by ronaldewatts** [comment]
![landlord_39_720p](https://user-images.githubusercontent.com/1394573/96375473-cd9a0600-113e-11eb-8b36-5b3abcced4b1.gif)
